---
- hosts: app
  become: yes

  tasks:
  - name: Ensure Chrony (for time synchronisation) is installed
    yum:
      name: chrony
      state: present

  - name: Ensure that chrony is running
    service:
      name: chronyd
      state: started
      enabled: yes
  
  - name: Ensure that pip is installed
    yum:
      name: python3-pip
      state: present

  - name: Ensure Django is installed
    pip:
      name: django<4
      state: present
